# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[kubernetes]
disabled = false

[gcloud]
disabled = true

[aws]
disabled = true

[time]
disabled = false
